### ISSUE TITLE
Gradle project Generation issue

### ISSUE THREAD

**Issue by Anand-Krish** [spring-io/initializr#1210]
I have user your starter io and initializer. I could able to successfully download maven dependency project from my localhost. But facing issue while choosing Gradle dependency. Couldn't able to download grade based project, source code is not getting generated for choosed dependency. Getting this below error. I am using version 0.10.0-SNAPSHOT

2021-03-26 14:59:02.673 INFO 13660 --- [)-10.98.163.224] o.s.web.servlet.DispatcherServlet : Initializing Servlet 'dispatcherServlet' 2021-03-26 14:59:02.678 INFO 13660 --- [)-10.98.163.224] o.s.web.servlet.DispatcherServlet : Completed initialization in 5 ms 2021-03-26 14:59:54.421 WARN 13660 --- [nio-8081-exec-9] i.s.i.g.p.ProjectGenerationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'maintenanceModuleHelpDocumentCustomizer' defined in class path resource [io/spring/start/site/extension/dependency/springcloud/SpringCloudProjectGenerationConfiguration.class]: Unsatisfied dependency expressed through method 'maintenanceModuleHelpDocumentCustomizer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gradleBuild' defined in class path resource [io/spring/initializr/generator/spring/build/gradle/GradleProjectGenerationConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.spring.initializr.generator.buildsystem.gradle.GradleBuild]: Factory method 'gradleBuild' threw exception; nested exception is java.lang.IllegalStateException: Bom 'org.springframework.boot:spring-boot-dependencies:2.2.0.RELEASE' could not be resolved 2021-03-26 14:59:54.442 ERROR 13660 --- [nio-8081-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'maintenanceModuleHelpDocumentCustomizer' defined in class path resource [io/spring/start/site/extension/dependency/springcloud/SpringCloudProjectGenerationConfiguration.class]: Unsatisfied dependency expressed through method 'maintenanceModuleHelpDocumentCustomizer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gradleBuild' defined in class path resource [io/spring/initializr/generator/spring/build/gradle/GradleProjectGenerationConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.spring.initializr.generator.buildsystem.gradle.GradleBuild]: Factory method 'gradleBuild' threw exception; nested exception is java.lang.IllegalStateException: Bom 'org.springframework.boot:spring-boot-dependencies:2.2.0.RELEASE' could not be resolved] with root cause

org.apache.http.conn.ConnectTimeoutException: Connect to repo1.maven.org:443 timed out at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:545) ~[httpclient-4.5.13.jar:4.5.13] at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:415) ~[httpclient-4.5.13.jar:4.5.13] at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.13.jar:4.5.13] at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326) ~[httpclient-4.5.13.jar:4.5.13] at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605) ~[httpclient-4.5.13.jar:4.5.13] at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440) ~[httpclient-4.5.13.jar:4.5.13] at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.13.jar:4.5.13] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.13.jar:4.5.13] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar:4.5.13] at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:164) ~[httpclient-4.5.13.jar:4.5.13] at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:290) ~[maven-resolver-transport-http-1.6.1.jar:1.6.1] at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:246) ~[maven-resolver-transport-http-1.6.1.jar:1.6.1] at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:67) ~[maven-resolver-spi-1.4.1.jar:1.4.1] at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457) ~[maven-resolver-connector-basic-1.6.1.jar:1.6.1] at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364) ~[maven-resolver-connector-basic-1.6.1.jar:1.6.1]

**Comment by wilkinsona** [comment]
The key part of the error is the following:

```
Connect to repo1.maven.org:443 timed out
```

There's a problem with your network which is prevent a connection to `repo1.maven.org` from being established.
