### ISSUE TITLE
Kotlin - Webflux generated projects lack dependency on io.projectreactor.addons.reactor-extra

### ISSUE THREAD

**Issue by agisbert** [spring-io/initializr#1305]
So this happened after I generated a project with spring initializer. https://start.spring.io/

I added the absolute minimum dependencies in it (see pic):

![image](https://user-images.githubusercontent.com/5805538/155141101-7308a03c-cbb4-48ab-9886-2fdbd752a20b.png)

The outcome is the following dependencies in the pom file:

```
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.module</groupId>
			<artifactId>jackson-module-kotlin</artifactId>
		</dependency>
		<dependency>
			<groupId>io.projectreactor.kotlin</groupId>
			<artifactId>reactor-kotlin-extensions</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-reflect</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-stdlib-jdk8</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlinx</groupId>
			<artifactId>kotlinx-coroutines-reactor</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

Now, conveniently, the `reactor-kotlin-extensions` library is added, offering many useful extension functions.

Most of them, depend on the `reactor-core` library, which is provided and also transitive, so no issue, but some of them, like repeat and retry, depend on `reactor-extra`. When using for instance the following extension function:

So, when using any of the extension functions for retry or repeats:

```
    fun postMovie(movie: Movie) =
        webClient
            .post()
            .uri("http://localhost:9009/movies")
            .body(Mono.just(movie))
            .retrieve()
            .toBodilessEntity()
            .retryExponentialBackoff(5, Duration.ofSeconds(1))
            .map {
                movie to true
            }.onErrorResume {
                println(it.message)
                Mono.just(movie to false)
            }
```

We get a nice NoClassDefFoundError:

```
java.lang.NoClassDefFoundError: reactor/retry/Retry
	at reactor.kotlin.extra.retry.RetryExtensionsKt.retryExponentialBackoff(RetryExtensions.kt:97) ~[reactor-kotlin-extensions-1.1.5.jar:1.1.5]
	at reactor.kotlin.extra.retry.RetryExtensionsKt.retryExponentialBackoff$default(RetryExtensions.kt:96) ~[reactor-kotlin-extensions-1.1.5.jar:1.1.5]
 ```

--- 

The issue has been reported here as well https://github.com/reactor/reactor-kotlin-extensions/issues/30 as a possible solution is changing the scope of the dependency from optional to compile, so it becomes a transitive dependency. However, since this is not solved yet, I would take temporarily an action of the following:

- Take the workaround described in the linked issue, adding `reactor-extra` as an additional dependency to the kotlin+Webflux generated projects. 
- Don't do it and leave this issue as documentation :)

**Comment by snicoll** [comment]
Moving to start.spring.io as this issue tracker is about the library, not our instance.
