### ISSUE TITLE
https://github.com/spring-io/initializr/issues/310#issue-188610357

### ISSUE THREAD

**Issue by dcyrille18** [spring-io/initializr#1484]
Refering to the same problem of the following issue https://github.com/spring-io/initializr/issues/310#issue-188610357

I'm trying to run the initializr-service behind a corporate proxy and I am getting some proxy exception, I resolved the one concerning the spring-boot versions by setting ```initializr.env.springBootMetadataUrl=""``` in the corresponding application.yml file but now, the next error arrived when I try to generate an archive.

Is it possible to have the archive of the desired spring-boot versions directly embedded in the jar ?

Thanks.

**Comment by snicoll** [comment]
@dcyrille18 setting the `initializr.env.springBootMetadataUrl` to an empty String is an outdated workaround, See [the reference guide](https://docs.spring.io/initializr/docs/current/reference/html/#create-instance-platform-versions).

In the sample, and in `sample.service.ServiceApplication` in particular, there is a `@Bean` method that you can remove to avoid retrieving the Spring Boot versions.

Now we have that out of the way, what is the "next error"?

**Comment by cdromas** [comment]
Sorry, I created this issue on the wrong project, I am currently working on the following "https://github.com/spring-io/start.spring.io", I don't know if you can move this issue ?

But, according to your recommandation I removed the variable "initializr.env.springBootMetadataUrl" from my application.yml and the bean you mentionned and it's already working for setting a predefined list of spring-boot version.

But now I have an some other errors due to my proxy, when I try to generate my project, such as, for example:
```
2023-11-19T14:12:08.820+01:00 ERROR 6198 --- [nio-8080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'settingsGradleProjectContributor' defined in class path resource [io/spring/initializr/generator/spring/build/gradle/GradleProjectGenerationConfiguration$GradleGroovyProjectGenerationConfiguration.class]: Unsatisfied dependency expressed through method 'settingsGradleProjectContributor' parameter 0: Error creating bean with name 'gradleBuild' defined in class path resource [io/spring/initializr/generator/spring/build/gradle/GradleProjectGenerationConfiguration.class]: Failed to instantiate [io.spring.initializr.generator.buildsystem.gradle.GradleBuild]: Factory method 'gradleBuild' threw exception with message: Bom 'org.springframework.boot:spring-boot-dependencies:3.1.5' could not be resolved] with root cause

java.net.UnknownHostException: repo1.maven.org: nodename nor servname provided, or not known
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934) ~[na:na]
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543) ~[na:na]
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306) ~[na:na]
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.14.jar!/:4.5.14]
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:442) ~[maven-resolver-transport-http-1.9.15.jar!/:1.9.15]
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:392) ~[maven-resolver-transport-http-1.9.15.jar!/:1.9.15]
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:64) ~[maven-resolver-spi-1.9.14.jar!/:1.9.14]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:482) ~[maven-resolver-connector-basic-1.9.15.jar!/:1.9.15]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414) ~[maven-resolver-connector-basic-1.9.15.jar!/:1.9.15]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260) ~[maven-resolver-connector-basic-1.9.15.jar!/:1.9.15]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:536) ~[maven-resolver-impl-1.9.14.jar!/:1.9.14]
```

I use the following command line to run the application:
```
java -XX:MinRAMPercentage=80.0 -XX:MaxRAMPercentage=90.0 -Dhttps.proxySet=true -Dhttp.proxyUser=myusername -Dhttp.proxyPassword=mypassword -Dhttp.proxyHost=myproxyhost.fr -Dhttp.proxyPort=80 -Dhttps.proxyUser=myusername -Dhttps.proxyPassword=mypassword -Dhttps.proxyHost=myproxyhost.fr -Dhttps.proxyPort=80 -jar start-site/target/start-site-exec.jar```

And I also tryied to set a m2 file with proxy configuration for my machine without any success.
