### ISSUE TITLE
A clean starter including only cloud-zuul and cloud-oauth2 does not run due to java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by johanvdb** [spring-io/initializr#244]
When creating a new project using only cloud-oauth2 and cloud-zuul as dependencies, the project compiles but crashes during startup with:

```
java.lang.NoSuchMethodError: org.springframework.cloud.netflix.zuul.filters.ProxyRequestHelper.setTraces(Lorg/springframework/boot/actuate/trace/TraceRepository;)V
```

I can see that spring-cloud-netflix-core 1.1.3 does not contain this method but 1.1.2 does. 

### Steps to reproduce:

Download the starter as per the following URL and extract it:

```
curl -o starter.zip 'http://start.spring.io/starter.zip?name=demo&groupId=com.example&artifactId=demo&version=0.0.1-SNAPSHOT&description=Demo+project+for+Spring+Boot&packageName=com.example&type=maven-project&packaging=jar&javaVersion=1.8&language=java&bootVersion=1.3.6.RELEASE&dependencies=cloud-oauth2&dependencies=cloud-zuul'
```

Compile

```
mvn package
```

Run

```
mvn spring-boot:run
```

The application will crash with the following root cause:
```
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.netflix.zuul.filters.ProxyRequestHelper.setTraces(Lorg/springframework/boot/actuate/trace/TraceRepository;)V
	at org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration$AuthenticationHeaderFilterConfiguration.authenticationHeaderFilter(OAuth2ProxyAutoConfiguration.java:79)
	at org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration$AuthenticationHeaderFilterConfiguration$$EnhancerBySpringCGLIB$$78e3c752.CGLIB$authenticationHeaderFilter$0(<generated>)
	at org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration$AuthenticationHeaderFilterConfiguration$$EnhancerBySpringCGLIB$$78e3c752$$FastClassBySpringCGLIB$$6b8e718b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration$AuthenticationHeaderFilterConfiguration$$EnhancerBySpringCGLIB$$78e3c752.authenticationHeaderFilter(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 25 more
```

**Comment by snicoll** [comment]
ping @spencergibb @dsyer

**Comment by dsyer** [comment]
https://github.com/spring-cloud/spring-cloud-security/issues/97

Spring Cloud Security 1.1.1.RELEASE was released yesterday to fix this.

**Comment by snicoll** [comment]
@johanvdb please report that in the spring cloud issue tracker next time. We can create an issue here if it turns out to be a configuration issue in initializr. Thanks!
