### ISSUE TITLE
Invalid meta-data if Sagan does not provide a default boot version

### ISSUE THREAD

**Issue by tan9** [spring-io/initializr#267]
I can not create new Spring Boot Starter projects from my IDE:

IntelliJ IDEA:
<img width="444" alt="sts" src="https://cloud.githubusercontent.com/assets/638068/17243133/875ea71e-55ad-11e6-9ca7-9ba5adc1d797.png">

STS:
<img width="457" alt="sts" src="https://cloud.githubusercontent.com/assets/638068/17243136/8b40885c-55ad-11e6-8ee1-31b446c16117.png">

And I paste the full url generated by STS:
http://start.spring.io/starter.zip?name=demo&groupId=com.example&artifactId=demo&version=0.0.1-SNAPSHOT&description=Demo+project+for+Spring+Boot&packageName=com.example&type=maven-project&packaging=jar&javaVersion=1.8&language=java

to browser, I got white label error page:

<img width="575" alt="whitelabel" src="https://cloud.githubusercontent.com/assets/638068/17243223/0ea7bb84-55ae-11e6-9ba9-49f8ff39f6b1.png">

saying:

> boot version must not be null

**Comment by snicoll** [comment]
Investigating....

**Comment by snicoll** [comment]
I think I've fixed production and I know what is going on. Can you try again please?

**Comment by tan9** [comment]
@snicoll Both IDEs can create start projects without problem! 👍

**Comment by snicoll** [comment]
OK so the problem was that when we released `1.4.0` we forgot to tick the default value. Sagan was giving us 4 boot  versions to use but none was declared as the default. It turns out that because we don't know what the default is, we won't set it if none is provided (that's the STS issue). If no default boot version is provided in the meta-data, IJ crashes. I've created [an issue in their tracker](https://youtrack.jetbrains.com/issue/IDEA-159177) for that.

On my side, I am changing the code so that it never happens again. We'll select the first version in the list as the default if non is provided.

**Comment by Codingshare** [comment]
We an see the same issue again. 
Initialization failed for 'https://start.spring.io'

**Comment by hussain21j** [comment]
The issue still remains

**Comment by wilkinsona** [comment]
It works for me. That's what I'd expect given the fix in https://github.com/spring-io/initializr/commit/d0187827269686945ce05ad1e3e9b705eb883c56 and the presence of a default  version in the current metadata:

```javascript
        {
            "apiDocUrl": "http://docs.spring.io/spring-boot/docs/2.0.3.RELEASE/api/",
            "artifactId": "spring-boot",
            "current": true,
            "generalAvailability": true,
            "groupId": "org.springframework.boot",
            "preRelease": false,
            "refDocUrl": "http://docs.spring.io/spring-boot/docs/2.0.3.RELEASE/reference/htmlsingle/",
            "releaseStatus": "GENERAL_AVAILABILITY",
            "snapshot": false,
            "version": "2.0.3.RELEASE",
            "versionDisplayName": "2.0.3"
        }
```

You may have an issue, @hussain21j, but I don't think it's this one.

**Comment by Codingshare** [comment]
That error is probably due to proxy setting.

**Comment by caozongpeng** [comment]
![image](https://user-images.githubusercontent.com/30362467/42682690-dfd7d94a-86bd-11e8-92dd-cdeccf0f419c.png)

**Comment by snicoll** [comment]
@caozongpeng please see the comment just before yours.

**Comment by helloyaoge** [comment]
![image](https://user-images.githubusercontent.com/12529019/83418409-21d56f80-a456-11ea-832c-ada0e1eb9eea.png)

**Comment by clintonpuge** [comment]
Done setting the proxy but still encountering the error.

**Comment by mahmutemrahsari** [comment]
Hi I have same problem with Intellij IDEA Ultimate 20201.1. Both windows and mac versions don`t work, @snicoll 

![Capture](https://user-images.githubusercontent.com/23225265/83429983-32c1b900-a435-11ea-9d49-3c663e48d8d3.PNG)

**Comment by wilkinsona** [comment]
It would appear that there's a hardcoded assumption about the format of Spring Boot's version number which is changed in 2.4 from 2.4.0.BUILD-SNAPSHOT to 2.4.0-SNAPSHOT. When this assumption is invalid, it breaks parsing of the metadata:

```
2020-06-01 18:09:41,937 [  18467]   INFO - arters.WebStarterOptionsLoader - Error processing JSON response from https://start.spring.io 
com.intellij.spring.boot.initializr.Version$InvalidVersionException: Could not determine version based on '2.4.0-M1': version format is Minor.Major.Patch.Qualifier (i.e. 1.0.5.RELEASE
        at com.intellij.spring.boot.initializr.Version.parse(Version.java:99)
        at com.intellij.spring.boot.initializr.VersionRange.parse(VersionRange.java:128)
        at com.intellij.spring.boot.initializr.SpringInitializrOptionsLoader.lambda$static$0(SpringInitializrOptionsLoader.java:47)
        at com.intellij.spring.boot.initializr.SpringInitializrOptionsLoader.createOptions(SpringInitializrOptionsLoader.java:195)
        at com.intellij.spring.boot.initializr.SpringInitializrOptionsLoader.parseDependencies(SpringInitializrOptionsLoader.java:153)
        at com.intellij.spring.boot.initializr.SpringInitializrOptionsLoader.parseJson(SpringInitializrOptionsLoader.java:118)
        at com.intellij.spring.boot.initializr.SpringInitializrModuleBuilder.parseOptionsDataJson(SpringInitializrModuleBuilder.java:229)
        at com.intellij.spring.boot.initializr.SpringInitializrModuleBuilder.parseOptionsDataJson(SpringInitializrModuleBuilder.java:46)
        at com.intellij.frameworks.starters.WebStarterOptionsLoader$1.process(WebStarterOptionsLoader.java:54)
        at com.intellij.frameworks.starters.WebStarterOptionsLoader$1.process(WebStarterOptionsLoader.java:34)
        at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
        at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
        at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
        at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
        at com.intellij.frameworks.starters.WebStarterOptionsLoader.loadOptions(WebStarterOptionsLoader.java:34)
        at com.intellij.frameworks.starters.WebStarterApplicationInfoStep.lambda$loadOptions$4(WebStarterApplicationInfoStep.java:102)
        at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
        at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I've temporarily removed 2.4.0-SNAPSHOT from the versions of Spring Boot that start.spring.io will offer. This will take a little while to update. Once 2.4 is no longer offered at https://start.spring.io, things should work again in IntelliJ IDEA.

**Comment by KevinWu97** [comment]
![image](https://user-images.githubusercontent.com/14934725/83435894-f5e0cc80-a40a-11ea-898b-9ea8a8f3d92e.png)

Having the same issue. Spring Initializr doesn't work.

**Comment by MirekKrenc** [comment]
I have the same issue

**Comment by DimaGilyov** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/52508760/83446471-edbf7600-a478-11ea-840d-6556734b6f10.png)

**Comment by Sebastianmueller22** [comment]
For me it was a transient error. Switched my wifi off and on again and now it works. Had internet the whole time though and no proxy active

**Comment by MathlouthiKhitem** [comment]
i have this error :Initialization failed for 'https://start.spring.io' Please check URL, network and proxy settings.  Error message: Cannot download 'https://start.spring.io': Connect timed out

**Comment by snicoll** [comment]
@MathlouthiKhitem this is likely to be a network problem on your end.
