### ISSUE TITLE
Local Spring Boot Version File

### ISSUE THREAD

**Issue by jonathanamartin** [spring-io/initializr#310]
I'm attempting to run the `initializr-service` locally behind a corporate proxy.   I'm getting the following exception:

```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://spring.io/project_metadata/spring-boot": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:633) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:287) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
...
```
Is there a way to default to use a local meta data file for spring boot versions without updating code?

**Comment by dsyer** [comment]
You can set `initializr.env.springBootMetadataUrl` to empty (or null), or to a location that you know will resolve correctly. Or you can provide a bean of type `InitializrMetadataProvider` to switch off the default one. Look at the source code in https://github.com/spring-io/initializr/blob/master/initializr-web/src/main/groovy/io/spring/initializr/web/autoconfigure/InitializrAutoConfiguration.groovy and https://github.com/spring-io/initializr/blob/master/initializr-generator/src/main/groovy/io/spring/initializr/metadata/InitializrConfiguration.groovy for more detail.

**Comment by jonathanamartin** [comment]
Sounds good.  Thanks.
