### ISSUE TITLE
Add Spring Cloud Gateway starter

### ISSUE THREAD

**Issue by spencergibb** [spring-io/initializr#522]
spring-cloud-starter-gateway

For Finchley

**Comment by snicoll** [comment]
@spencergibb please provide more details. If you believe that an entry is deserved for this starter, a description for it is the bare minimum. Thanks

**Comment by joshlong** [comment]
Hi, 
It is an API gateway like Zuul. It's Maven coordinates are: 

`org.springframework.cloud</groupId>` :  `spring-cloud-starter-gateway`  

It's managed by the Spring Cloud BOM (`org.springframework.cloud` : `spring-cloud-dependencies`). 

It requires Spring Cloud Finchley which in turn requires Spring Boot 2.0. 

Possible description is: `Intelligent API gateway and proxy with Spring Cloud Gateway`

**Comment by snicoll** [comment]
Thanks for the feedback! I've tried a `Gateway` entry in the same group as zuul

```
- name: Gateway
  id: cloud-gateway
  groupId: org.springframework.cloud
  artifactId: spring-cloud-starter-gateway
  description: Effective way to route to APIs and provide cross cutting concerns to them
```

If someone has a link to a sample or documentation we can add links there, just paste them here.

The starter does not work with the milestone at the moment

```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.gateway.config.GatewayAutoConfiguration] from ClassLoader [java.net.URLClassLoader@20564a99]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:659)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:556)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:541)
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:728)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:670)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:638)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1507)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1025)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:168)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanType(BeanTypeRegistry.java:157)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.updateTypesIfNecessary(BeanTypeRegistry.java:207)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:114)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:265)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:254)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:196)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:115)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	... 22 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/server/handler/WebHandlerDecorator
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:641)
	... 39 more
Caused by: java.lang.ClassNotFoundException: org.springframework.web.server.handler.WebHandlerDecorator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 more
```

Let's revisit this once Spring Cloud has a milestone release that works against a recent Spring Boot milestone.

**Comment by snicoll** [comment]
We can but I don't want to promote something that doesn't work with at least a milestone. It's not like Spring Cloud Gateway was new or something, it is effectively broken with Spring Boot 2 M.

As soon as Spring Cloud has a `Finchley` milestone that works with the last Boot's milestone, I am happy to add it.

**Comment by snicoll** [comment]
@spencergibb can you provide a link to the doc and a link to a sample please. That would improve the metadata of the entry

**Comment by snicoll** [comment]
@spencergibb ping? Can you help @starbuxman adding the links I've requested in my last comment? See, #531, thanks.

**Comment by joshlong** [comment]
If you add `spring-boot-starter-webflux` it works.  Gateway also exists in Edgeware, doesn't exclusively require Finchely. It also exists in older milestones of Spring Cloud. So if you had added `spring-boot-starter-webflux` to a stock demo then it would work for Finchley M2.  (doesn't even need snapshots). Does that change the consideration of its inclusion?

**Comment by snicoll** [comment]
That's not what @spencergibb originally requested so I don't know if that's an omission or if he really meant Finchley. Why the rush? I'd rather announce something that has a chance to work OOB rather than the exception I've seen when I tried. 

I am also waiting for links to doc and sample (see above).

**Comment by spencergibb** [comment]
Sample: https://github.com/spring-cloud-samples/spring-cloud-gateway-sample
Docs: http://cloud.spring.io/spring-cloud-gateway/

There is no starter for Edgware. If we want something for Edgware it would be a different artifact /cc @dsyer 

Finchley.M3 will be likely tomorrow.

**Comment by snicoll** [comment]
@spencergibb if I understand correctly there are two "flavours" of the gateway. A webflux-based on an [an mvc based one](https://github.com/spring-cloud/spring-cloud-gateway/blob/master/spring-cloud-gateway-mvc/pom.xml). The  gateway starter brings the webflux starter.

If Spring Cloud Gateway supports two different use cases, I'd like that the user chooses gateway + web or webflux depending on their needs. If I misunderstood, can you please clarify?

**Comment by spencergibb** [comment]
There's only a starter for the reactive one. That's all this issue is asking for.

**Comment by snicoll** [comment]
So the answer to my question is that Spring Cloud Gateway always requires webflux and that MVC support is unrelated to the runtime requirement.
