### ISSUE TITLE
Basedir with subdirectory broken

### ISSUE THREAD

**Issue by dsyer** [spring-io/initializr#81]
```
$ curl localhost:8080/starter.tgz -d baseDir=target/test | tar -xzvf -
```

Boom:

```
2015-02-24 12:25:11.208 ERROR 8198 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.io.FileNotFoundException: ./tmp1007850392529924022/target/test/pom.xml (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.write(ResourceGroovyMethods.java:713)
	at org.codehaus.groovy.runtime.dgm$888.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at io.spring.initializr.ProjectGenerator.generateProjectStructure(ProjectGenerator.groovy:90)
...
```

**Comment by snicoll** [comment]
you want to create an archive with the root baseDir as `target` and place the project in a `test` sub-directory I guess?

**Comment by dsyer** [comment]
Yes.
