### ISSUE TITLE
Forwarding to error page from request [/starter.zip]due to exception [String index out of range: -1]

### ISSUE THREAD

**Issue by weishi2010** [spring-io/initializr#827]
`Forwarding to error page from request [/starter.zip]due to exception [String index out of range: -1]`

It happened in linux environment. Exception is threw from this class:

```
io.spring.initializr.generator.project.contributor.MultipleResourcesProjectContributor.contribute(MultipleResourcesProjectContributor.java:59)
```

```
String filename =resource.getURI().toString().substring(root.getURI().toString().length()+1);
```

if your java project run in the linux environment，the rootResource will get "/" in last char，so the exception will happen in this time. so I modified it like this

```
String filename =resource.getURI().toString().substring(root.getURI().toString().length());
```

when java project run in the linux environment.

**Comment by snicoll** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

Thanks for the report but I'd like to get more information about the error. How can I reproduce this issue? start.spring.io runs on Linux so there is a piece of information that you've not shared. Thanks

**Comment by weishi2010** [comment]
> I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.
> 
> Thanks for the report but I'd like to get more information about the error. How can I reproduce this issue? start.spring.io runs on Linux so there is a piece of information that you've not shared. Thanks

**Comment by weishi2010** [comment]
2019-02-13 09:42:23.261 ERROR 88891 --- [http-nio-1601-exec-7] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/starter.zip] due to exception [String index out of range: -1]

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1918) ~[na:1.8.0_20]
	at io.spring.initializr.generator.project.contributor.MultipleResourcesProjectContributor.contribute(MultipleResourcesProjectContributor.java:59) ~[initializr-generator-0.8.0.BUILD-SNAPSHOT.jar:na]
	at io.spring.initializr.generator.project.DefaultProjectAssetGenerator.generate(DefaultProjectAssetGenerator.java:47) ~[initializr-generator-0.8.0.BUILD-SNAPSHOT.jar:na]
	at io.spring.initializr.web.project.ProjectGenerationInvoker.lambda$generateProject$1(ProjectGenerationInvoker.java:102) ~[initializr-web-0.8.0.BUILD-SNAPSHOT.jar:na]
	at io.spring.initializr.web.project.ProjectGenerationInvoker$$Lambda$440/1283823349.generate(Unknown Source) ~[na:na]
	at io.spring.initializr.generator.project.ProjectGenerator.generate(ProjectGenerator.java:67) ~[initializr-generator-0.8.0.BUILD-SNAPSHOT.jar:na]
	at io.spring.initializr.web.project.ProjectGenerationInvoker.invokeProjectStructureGeneration(ProjectGenerationInvoker.java:87) ~[initializr-web-0.8.0.BUILD-SNAPSHOT.jar:na]
	at io.spring.initializr.web.project.MainController.springZip(MainController.java:265) ~[initializr-web-0.8.0.BUILD-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[servlet-api.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.30]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.30]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.30]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.30]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.30]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:105) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:123) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.30]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.30]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.30]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.30]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.30]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.30]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.30]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.30]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521) [catalina.jar:8.0.30]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096) [tomcat-coyote.jar:8.0.30]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674) [tomcat-coyote.jar:8.0.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-coyote.jar:8.0.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-coyote.jar:8.0.30]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.30]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]

**Comment by weishi2010** [comment]
> I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.
> 
> Thanks for the report but I'd like to get more information about the error. How can I reproduce this issue? start.spring.io runs on Linux so there is a piece of information that you've not shared. Thanks

`	@Override
	public void contribute(Path projectRoot) throws IOException {
		Resource root = this.resolver.getResource(this.rootResource);
		Resource[] resources = this.resolver.getResources(this.rootResource + "/**");
		for (Resource resource : resources) {
			String filename = resource.getURI().toString()
					.substring(root.getURI().toString().length());
			if (resource.isReadable()) {
				Path output = projectRoot.resolve(filename);
				Files.createDirectories(output.getParent());
				Files.createFile(output);
				FileCopyUtils.copy(resource.getInputStream(),
						Files.newOutputStream(output));
				// TODO Set executable using NIO
				output.toFile().setExecutable(this.executable.test(filename));
			}
		}
	}`

The root object's uri  is "/export/App/demo/WEB-INF/lib/initializr-generator-spring-0.8.0.BUILD-SNAPSHOT.jar!/maven/wrapper"  in the Windows enviroment，
but in linux，it just like this "/export/App/demo/WEB-INF/lib/initializr-generator-spring-0.8.0.BUILD-SNAPSHOT.jar!/maven/wrapper/"

So，
`String filename = resource.getURI().toString().substring(root.getURI().toString().length()+1);`

This code will throw exception when it's running.
`java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1918) ~[na:1.8.0_20]
at io.spring.initializr.generator.project.contributor.MultipleResourcesProjectContributor.contribute(MultipleResourcesProjectContributor.java:59)`

**Comment by snicoll** [comment]
@weishi2010 sorry but that still does not answer my question. I don't get how you manage to get a resource object with uri identical to the root as what the contributor is requesting is nested resources. 

Are you running a custom instance or is it the current `master`? Can you explain how I can reproduce this?

**Comment by weishi2010** [comment]
> @weishi2010 sorry but that still does not answer my question. I don't get how you manage to get a resource object with uri identical to the root as what the contributor is requesting is nested resources.
> 
> Are you running a custom instance or is it the current `master`? Can you explain how I can reproduce this?

A custom instance，my project depends on the "initializr-web" dependency  and it's version is 0.8.0.BUILD-SNAPSHOT。
![image](https://user-images.githubusercontent.com/16144884/52832747-d5590a00-3114-11e9-8577-85eabc7f7aae.png)

**Comment by snicoll** [comment]
@weishi2010 unless you provide a sample that helps me reproduce this issue, I am afraid I'll have to close this as I don't understand how you end up in the situation that you've described.

If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by weishi2010** [comment]
[local-initializr.zip](https://github.com/spring-io/initializr/files/2868668/local-initializr.zip)

Thank you!

**Comment by snicoll** [comment]
@weishi2010 thanks for the sample. How do I reproduce the issue?

**Comment by weishi2010** [comment]
You can deploy this sample in Linux and generate a project.

![image](https://user-images.githubusercontent.com/16144884/52848586-1586af80-314a-11e9-92a5-a38eddcde02f.png)

You will get  this error page!

**Comment by snicoll** [comment]
Please try to be a bit more specifc. What do you mean by "deploy this sample"?

**Comment by weishi2010** [comment]
Running in Linux with this sample.

**Comment by snicoll** [comment]
"Running in Linux"  is not helping either and we've spent more time getting the information than actually working on a fix. 

I can reproduce the issue when deploying to an existing container.

**Comment by weishi2010** [comment]
> "Running in Linux" is not helping either and we've spent more time getting the information than actually working on a fix.
> 
> I can reproduce the issue when deploying to an existing container.

Thank you!
