### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by kuanox** [spring-io/initializr#859]
Hi

 When i run this command ./mvnw clean install, i have a error test... (likewise in IntelliJ)

```
[ERROR] Tests run: 5, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in io.spring.initializr.generator.io.IndentingWriterTests
[ERROR] linesCanBeIndented  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <"a
    b
c
">
to be equal to:
 <"a
    b
c
">
but was not.
	at io.spring.initializr.generator.io.IndentingWriterTests.linesCanBeIndented(IndentingWriterTests.java:51)

[ERROR] useOfPrintDoesNotAddIndent  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <"a
    bbb
c
">
to be equal to:
 <"a
    bbb
c
">
but was not.
	at io.spring.initializr.generator.io.IndentingWriterTests.useOfPrintDoesNotAddIndent(IndentingWriterTests.java:74)

[ERROR] blankLinesAreNotIndented  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <"a
    b

c
">
to be equal to:
 <"a
    b

c
">
but was not.
	at io.spring.initializr.generator.io.IndentingWriterTests.blankLinesAreNotIndented(IndentingWriterTests.java:62)

[ERROR] customIndentStrategyIsUsed  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <"a
	b
		ce
">
to be equal to:
 <"a
	b
		ce
">
but was not.
	at io.spring.initializr.generator.io.IndentingWriterTests.customIndentStrategyIsUsed(IndentingWriterTests.java:90)

[ERROR] linesAreNotIndentedByDefault  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <"a
b
c
">
to be equal to:
 <"a
b
c
">
but was not.
	at io.spring.initializr.generator.io.IndentingWriterTests.linesAreNotIndentedByDefault(IndentingWriterTests.java:43)
```

I have java 8, and i use Maven on IntelliJ

I see the Test but is "ok", i not know why not work

Regards

**Comment by snicoll** [comment]
Do I assume correctly you are running this on Windows?

**Comment by kuanox** [comment]
> Do I assume correctly you are running this on Windows?

Yes Sr. , is Windows 10

**Comment by snicoll** [comment]
@kuanox thanks for the feedback and reporting the issue. The where some assertions that were assuming newline to be `\n`.

**Comment by kuanox** [comment]
> @kuanox thanks for the feedback and reporting the issue. They were some assertions that were assuming newline to be `\n`.

OK, Thanks You.
